### ISSUE TITLE
有需要開啟 polyfills 裡面針對 IE 的設定嗎？

### ISSUE THREAD

**Issue by poychang** [augt/angular.tw#32]
目前 IE 的支援還是很悲劇，不開啟 polyfills.js 裡面針對 IE 做的填充，網站整個會開不起來，各位大大覺得有需要開啟嗎？

**Comment by chgc** [comment]
有那個需要，我沒有開啟嗎?

**Comment by poychang** [comment]
https://github.com/augt/angular.tw/blob/master/src/polyfills.ts#L21
沒有耶～

**Comment by chgc** [comment]
已開啟了
